/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["post_UserRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["post_UserLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated user profile */
        get: operations["get_UserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create immutable commit with blob */
        post: operations["post_CommitCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookmarks for authenticated user */
        get: operations["get_BookmarkList"];
        put?: never;
        /** Set bookmark (upsert by name) */
        post: operations["post_BookmarkCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/{bookmarkName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bookmark by name */
        get: operations["get_BookmarkFetch"];
        put?: never;
        post?: never;
        /** Delete bookmark */
        delete: operations["delete_BookmarkDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_UserRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                    turnstileToken: string;
                };
            };
        };
        responses: {
            /** @description Registered user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        user: {
                            username: string;
                            /** Format: date-time */
                            createdOn: string;
                            quotaBytesUsed: number;
                            quotaBytesLimit: number;
                        };
                    };
                };
            };
            /** @description Turnstile verification failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    post_UserLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                    turnstileToken: string;
                };
            };
        };
        responses: {
            /** @description JWT token and user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        token: string;
                        user: {
                            username: string;
                            /** Format: date-time */
                            createdOn: string;
                            quotaBytesUsed: number;
                            quotaBytesLimit: number;
                        };
                    };
                };
            };
            /** @description Turnstile verification failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_UserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        user: {
                            username: string;
                            /** Format: date-time */
                            createdOn: string;
                            quotaBytesUsed: number;
                            quotaBytesLimit: number;
                        };
                    };
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    post_CommitCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Blob persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        status: "created" | "exists";
                    };
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
            /** @description User or parent commit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
            /** @description Storage quota exceeded */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_BookmarkList: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmarks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        bookmarks: {
                            name: string;
                            commit: string;
                            /** Format: date-time */
                            createdOn: string;
                        }[];
                    };
                };
            };
        };
    };
    post_BookmarkCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    commit: string;
                };
            };
        };
        responses: {
            /** @description Created bookmark */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        bookmark: {
                            name: string;
                            commit: string;
                            /** Format: date-time */
                            createdOn: string;
                        };
                    };
                };
            };
            /** @description Commit not found */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_BookmarkFetch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bookmark name */
                bookmarkName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        bookmark: {
                            name: string;
                            commit: string;
                            /** Format: date-time */
                            createdOn: string;
                        };
                    };
                };
            };
            /** @description Bookmark not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    delete_BookmarkDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bookmark name */
                bookmarkName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        deleted: boolean;
                    };
                };
            };
        };
    };
}
