/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["post_UserRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["post_UserLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commits/{commitHash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get commit metadata by hash */
        get: operations["get_CommitFetch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commits/data/{blobHash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get raw blob data for a blob hash */
        get: operations["get_CommitDataFetch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commits/{commitHash}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get commit metadata and blob data together (msgpack encoded) */
        get: operations["get_CheckoutFetch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated user profile */
        get: operations["get_UserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user settings */
        get: operations["get_SettingsFetch"];
        put?: never;
        /** Save user settings */
        post: operations["post_SettingsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/keybindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get custom keybindings */
        get: operations["get_KeybindingFetch"];
        put?: never;
        /** Save custom keybindings */
        post: operations["post_KeybindingCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List commits for authenticated user (incremental sync) */
        get: operations["get_UserCommitList"];
        put?: never;
        /** Create immutable commit with blob */
        post: operations["post_CommitCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookmarks for authenticated user */
        get: operations["get_BookmarkList"];
        put?: never;
        /** Set bookmark (upsert by name) */
        post: operations["post_BookmarkCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/bookmarks/{bookmarkName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bookmark by name */
        get: operations["get_BookmarkFetch"];
        put?: never;
        post?: never;
        /** Delete bookmark */
        delete: operations["delete_BookmarkDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_UserRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                    turnstileToken: string;
                };
            };
        };
        responses: {
            /** @description Registered user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        user: {
                            username: string;
                            /** Format: date-time */
                            createdOn: string;
                            quotaBytesUsed: number;
                            quotaBytesLimit: number;
                        };
                    };
                };
            };
            /** @description Turnstile verification failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    post_UserLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                    turnstileToken: string;
                };
            };
        };
        responses: {
            /** @description JWT token and user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        token: string;
                        user: {
                            username: string;
                            /** Format: date-time */
                            createdOn: string;
                            quotaBytesUsed: number;
                            quotaBytesLimit: number;
                        };
                    };
                };
            };
            /** @description Turnstile verification failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_CommitFetch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SHA-256 commit hash (hex) */
                commitHash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commit metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        commit: {
                            blob: string;
                            createdOn: number;
                            parent?: string;
                            editorVersion: string;
                            libraries: {
                                name: string;
                                version: string;
                            }[];
                            author: string;
                        };
                    };
                };
            };
            /** @description Commit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_CommitDataFetch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SHA-256 blob hash (hex) */
                blobHash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw deflate-compressed blob bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Invalid blob hash */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
            /** @description Blob not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_CheckoutFetch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SHA-256 commit hash (hex) */
                commitHash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description msgpack-encoded object: { commit: StoredCommit, data: Uint8Array } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Commit or blob not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_UserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        user: {
                            username: string;
                            /** Format: date-time */
                            createdOn: string;
                            quotaBytesUsed: number;
                            quotaBytesLimit: number;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            /** @enum {string} */
                            code: "USER_NOT_FOUND";
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_SettingsFetch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        settings: {
                            [key: string]: unknown;
                        } | null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
            /** @description Invalid data stored */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: string;
                    };
                };
            };
        };
    };
    post_SettingsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Settings saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_KeybindingFetch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom keybindings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        keybindings: {
                            key: string;
                            command: string;
                            remove?: boolean;
                            when?: ("editor" | "sandbox")[];
                        }[] | null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
            /** @description Invalid data stored */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: string;
                    };
                };
            };
        };
    };
    post_KeybindingCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    key: string;
                    command: string;
                    remove?: boolean;
                    when?: ("editor" | "sandbox")[];
                }[];
            };
        };
        responses: {
            /** @description Keybindings saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_UserCommitList: {
        parameters: {
            query?: {
                /** @description Get all commits after a given sequence number */
                seq?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commits with sequence numbers for incremental sync */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        commits: {
                            seq: number;
                            hash: string;
                            parent: string | null;
                            createdOn: number;
                            blob: string;
                            editorVersion: string;
                            libraries: {
                                name: string;
                                version: string;
                            }[];
                        }[];
                        nextSeq: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
        };
    };
    post_CommitCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Blob persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        status: "created" | "exists";
                        size?: number;
                    };
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
            /** @description User or parent commit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
            /** @description Storage quota exceeded */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_BookmarkList: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmarks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        bookmarks: {
                            name: string;
                            commit: string;
                            createdOn: number;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
        };
    };
    post_BookmarkCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    commit: string;
                };
            };
        };
        responses: {
            /** @description Created bookmark */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        bookmark: {
                            name: string;
                            commit: string;
                            createdOn: number;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
        };
    };
    get_BookmarkFetch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bookmark name */
                bookmarkName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookmark */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        bookmark: {
                            name: string;
                            commit: string;
                            createdOn: number;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
            /** @description Bookmark not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        error: {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
    };
    delete_BookmarkDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Bookmark name */
                bookmarkName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        deleted: boolean;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: false;
                        error: {
                            code: "UNAUTHORIZED" | "INVALID_USER_ID";
                            message: string;
                        };
                    };
                };
            };
        };
    };
}
